config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'posts/index'

  root 'posts#index', as: 'home'

  resources :posts do
    resources :comments
    end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :comments, dependent: :delete_all
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:create]

  def index
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/posts_controller.rb
#noinspection RubyInterpreter
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
  	@posts = Post.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.save
	  redirect_to @post
  end

  def edit
  	@post = Post.find(params[:id])	
  end

  def update
  	@post = Post.find(params[:id])
  	@post.update(post_params)
	redirect_to @post
  end

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy
  	redirect_to posts_path
  end

  private
     def  post_params
     	params.require(:post).permit(:title,:body,:author)
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!--    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>-->
  <!--    <script>tinymce.init({selector:'textarea'});</script>-->
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark  ">
  <a class="navbar-brand" href="#">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", home_path, class: "nav-link" %>
      </li>




      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "New Post", new_post_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link btn btn-dark ") %>
        </li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path, class: "nav-link") %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>

app/views/posts/edit.html.erb
<div class="container" >
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h3> Edit Post</h3>
      <hr/>
      <%= form_for :post, url: post_path(@post), method: :patch, :html => {:class => "form-horizontal"} do |f| %>
        <p>
          <%= f.label :title %><br>
          <%= f.text_field :title, class: 'form-control' %>
        </p>
        <p>
          <%= f.label :body %><br>
          <%= f.text_area :body, class: 'form-control' %>
        </p>
        <p>
          <%= f.label :author %><br>
          <%= f.text_field :author, class: 'form-control' %>
        </p>

        <p>
          <%= f.submit %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3>All Posts</h3>
      <hr/>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <td><b>User</b></td>
            <td><b>Title</b></td>
            <td><b>Body</b></td>
            <td><b>Author</b></td>
            <td><b>Action</b></td>
          </tr>
        </thead>
        <tbody>
        <% @posts.each do |post| %></h1>
          <tr>
            <td><%= post.user.email %></td>
            <td><%= post.title %></td>
            <td><%= post.body %></td>
            <td><%= post.author %></td>
            <td><%= link_to "Go To Post", post_path(post), :class => 'btn btn-primary' %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h3> Add Post</h3>
      <hr/>
      <%= form_for :post, url: posts_path, :html => {:class => "form-horizontal"} do |f| %>
        <p>
          <%= f.label :title %><br>
          <%= f.text_field :title, class: 'form-control' %>
        </p>
        <p>
          <%= f.label :body %><br>
          <%= f.text_area :body, class: 'form-control' %>
        </p>
        <%= f.label :author %><br>
        <%= f.text_field :author, class: 'form-control' %>
        </p>
        <p>
          <%= f.submit %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h3>Details about the post</h3>
      <hr/>
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <td><b>Title</b></td>
          <td><b>Body</b></td>
          <td><b>Author</b></td>
          <td><b>Action</b></td>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= @post.title %></td>
          <td><%= @post.body %></td>
          <td><%= @post.author %></td>
          <td><%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-primary'%>
            <%= link_to "Delete", post_path(@post),
                        method: :delete,
                        :class => 'btn btn-danger'%></td>
        </tr>
        </tbody>
      </table>





      <% if @post.comments.length > 0 %>
        <hr>
      <h3>Comments about the post</h3>
      <hr>
      <% @post.comments.each do |comment| %>
          <div class="card card-white post">
            <div class="post-heading">
              <div class="float-left image">
                <img height="50px" src="http://bootdey.com/img/Content/user_1.jpg" class="img-circle avatar" alt="user profile image">
              </div>
              <div class="float-left meta">
                <div class="title h5">
                  <a href="#"><b><%= comment.name %></b></a>
                </div>
              </div>
            </div>
            <div class="post-description">
              <p><%= comment.body %></p>
            </div>
            <%= link_to 'Remove Comment',[comment.post,comment], method: :delete %>
          </div>
      <% end %>
      <br>
      <% end %>

      <hr>
      <h3>Add Comment</h3>
      <hr>
      <%= form_for ([@post,@post.comments.build]) do |f| %>
        <p>
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </p>
        <p>
          <%= f.label :body %><br>
          <%= f.text_area :body, class: 'form-control' %>
        </p>
        <p>
          <%= f.submit  :class => 'btn btn-primary'%>
        </p>
      <% end %>
    </div>
  </div>
</div>